# Generated by Django 5.0.3 on 2024-03-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_customuser_created_at_customuser_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
