# Generated by Django 5.0.3 on 2024-03-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_customuser_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=5),
        ),
    ]
