# Generated by Django 5.0.3 on 2024-03-15 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ride",
            options={"verbose_name": "Ride", "verbose_name_plural": "Rides"},
        ),
        migrations.AlterModelOptions(
            name="ridehistory",
            options={
                "verbose_name": "Ride History",
                "verbose_name_plural": "Ride History",
            },
        ),
        migrations.RenameField(
            model_name="ridehistory",
            old_name="joined_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="ridehistory",
            old_name="left_at",
            new_name="updated_at",
        ),
    ]
