# Generated by Django 5.0.3 on 2024-03-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
