# Generated by Django 5.0.3 on 2024-03-14 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="driver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
