# Generated by Django 5.0.3 on 2024-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0002_alter_vehicle_driver_alter_vehicle_license_plate"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_busy",
            field=models.BooleanField(default=False),
        ),
    ]
